server:
  port: 8081
  context-path: /eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/eureka/ #默认区域的配置，需要带上eureka模块的上下文，例如第一个eureka就是上下文。eureka和service和zuul的defaultZone应该保持一致，否则service和zuul注册不上。