spring:
  application:
    name: api1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/eureka/ #默认区域的配置，eureka和service和zuul应该保持一致
server:
  port: 8082
  context-path: /api1